services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_URI: mongodb://mongo:27017/native-ecommerce
      MEDIA_DIR: /app/media
    volumes:
      - media:/app/media

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
  media:
